# Generated by Django 5.2.7 on 2025-10-03 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planejado'), ('IN_PROGRESS', 'Em Andamento'), ('EDITING', 'Em Edição'), ('COMPLETED', 'Concluído'), ('ARCHIVED', 'Arquivado')], default='PLANNED', max_length=20)),
                ('project_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.client')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
